"""Describe a training job and generate the commands/scripts that run it on a rented GPU box.

Two backends:
  - "mixle": run a user-provided training script with `mixle` installed (it writes a model artifact).
  - "llm":   fine-tune a HuggingFace model with LoRA (transformers + peft + trl), generated here.
"""
from __future__ import annotations

import shlex
from dataclasses import dataclass, field

DEFAULT_IMAGE = "pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime"

# The mixle core is installed on the box from git by default (the box can `git clone` the public
# repo) so it gets the current code, not a pinned PyPI release. Override per-job via --mixle-git.
DEFAULT_MIXLE_SPEC = "git+https://github.com/gmboquet/mixle.git@evolve"
LLM_PACKAGES = ["transformers>=4.44", "peft>=0.12", "datasets>=2.20", "accelerate>=0.33", "bitsandbytes>=0.43", "sentencepiece"]


@dataclass
class TrainingJob:
    name: str
    backend: str = "mixle"          # "mixle" | "llm"
    mode: str = "ssh"               # "ssh" | "onstart"
    # code/data
    workdir: str | None = None      # local dir to upload (ssh mode)
    repo: str | None = None         # git URL to clone (onstart mode)
    script: str | None = None       # entry script (mixle backend), relative to the work dir
    dataset: str | None = None      # jsonl path (uploaded, ssh) or HF dataset name / URL (onstart)
    output: str = "artifact"        # where the job writes its model, on the box
    # llm backend
    base_model: str | None = None
    epochs: float = 1.0
    qlora: bool = False
    # provisioning
    gpu: str = "RTX_4090"
    num_gpus: int = 1
    max_price: float = 1.5
    disk: int = 40
    image: str | None = None
    requirements: list[str] = field(default_factory=list)
    mixle_spec: str = DEFAULT_MIXLE_SPEC   # pip requirement for the mixle core (git URL or "mixle>=x")
    # lifecycle
    register: bool = True
    max_runtime_min: int = 60       # hard cap: destroy the box after this many minutes no matter what

    def validate(self) -> None:
        if self.backend not in ("mixle", "llm"):
            raise ValueError("backend must be 'mixle' or 'llm'")
        if self.mode not in ("ssh", "onstart"):
            raise ValueError("mode must be 'ssh' or 'onstart'")
        if self.backend == "mixle" and not self.script:
            raise ValueError("mixle backend requires --script (the training entry point)")
        if self.backend == "llm" and not self.base_model:
            raise ValueError("llm backend requires --base-model")
        if self.mode == "ssh" and not self.workdir and self.backend == "mixle":
            raise ValueError("ssh mode for the mixle backend requires --workdir to upload")
        if self.mode == "onstart" and not self.repo and self.backend == "mixle":
            raise ValueError("onstart mode for the mixle backend requires --repo to clone")


def resolve_image(job: TrainingJob) -> str:
    return job.image or DEFAULT_IMAGE


def pip_packages(job: TrainingJob) -> list[str]:
    base = LLM_PACKAGES if job.backend == "llm" else [job.mixle_spec]
    return [*base, *job.requirements]


def training_command(job: TrainingJob, workdir: str = ".") -> str:
    """The shell command that runs the training, relative to `workdir` on the box."""
    out = shlex.quote(job.output)
    if job.backend == "llm":
        parts = [
            "python", "llm_lora_train.py",
            "--base_model", shlex.quote(job.base_model or ""),
            "--output", out,
            "--epochs", str(job.epochs),
        ]
        if job.dataset:
            parts += ["--dataset", shlex.quote(job.dataset)]
        if job.qlora:
            parts += ["--qlora"]
        return " ".join(parts)
    # mixle backend: run the user's script; pass --output/--dataset by convention
    parts = ["python", shlex.quote(job.script or "")]
    if job.dataset:
        parts += ["--dataset", shlex.quote(job.dataset)]
    parts += ["--output", out]
    return " ".join(parts)


# Generated LoRA fine-tuning script (shipped to the box / run locally for the "llm" backend).
# Uses transformers Trainer + peft directly (stable across versions, runs on CPU/MPS/CUDA).
LLM_LORA_SCRIPT = '''\
"""LoRA fine-tune via transformers Trainer + peft. Generated by mixle-mlops."""
import argparse
from datasets import load_dataset
from peft import LoraConfig, get_peft_model
from transformers import (AutoModelForCausalLM, AutoTokenizer, DataCollatorForLanguageModeling,
                          Trainer, TrainingArguments)

p = argparse.ArgumentParser()
p.add_argument("--base_model", required=True)
p.add_argument("--dataset", required=True, help="a .jsonl file with a 'text' field, or a HF dataset id")
p.add_argument("--output", default="artifact")
p.add_argument("--epochs", type=float, default=1.0)
p.add_argument("--max_seq_len", type=int, default=512)
p.add_argument("--batch_size", type=int, default=1)
p.add_argument("--lr", type=float, default=2e-4)
p.add_argument("--lora_r", type=int, default=16)
p.add_argument("--lora_alpha", type=int, default=32)
p.add_argument("--qlora", action="store_true")
a = p.parse_args()

ds = (load_dataset("json", data_files=a.dataset, split="train")
      if a.dataset.endswith(".jsonl") else load_dataset(a.dataset, split="train"))

tok = AutoTokenizer.from_pretrained(a.base_model)
if tok.pad_token is None:
    tok.pad_token = tok.eos_token

text_col = "text" if "text" in ds.column_names else ds.column_names[0]
def _tok(batch):
    return tok(batch[text_col], truncation=True, max_length=a.max_seq_len)
ds_tok = ds.map(_tok, batched=True, remove_columns=ds.column_names)

model_kwargs = {}
if a.qlora:
    import torch
    from transformers import BitsAndBytesConfig
    model_kwargs = {"device_map": "auto", "quantization_config": BitsAndBytesConfig(
        load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type="nf4")}
model = AutoModelForCausalLM.from_pretrained(a.base_model, **model_kwargs)
model = get_peft_model(model, LoraConfig(
    r=a.lora_r, lora_alpha=a.lora_alpha, target_modules="all-linear", task_type="CAUSAL_LM"))
model.print_trainable_parameters()

args = TrainingArguments(output_dir=a.output, num_train_epochs=a.epochs,
    per_device_train_batch_size=a.batch_size, learning_rate=a.lr, logging_steps=5,
    save_strategy="no", report_to=[])
trainer = Trainer(model=model, args=args, train_dataset=ds_tok,
                  data_collator=DataCollatorForLanguageModeling(tok, mlm=False))
trainer.train()
model.save_pretrained(a.output)
tok.save_pretrained(a.output)
print("SAVED_ADAPTER", a.output)
'''


def build_onstart(job: TrainingJob, s3_dest: str | None = None) -> str:
    """A self-contained startup script for fire-and-forget runs (clone, train, upload, mark done)."""
    lines = ["#!/bin/bash", "set -euo pipefail", "cd /workspace 2>/dev/null || (mkdir -p /workspace && cd /workspace)"]
    lines.append("pip install -q " + " ".join(shlex.quote(p) for p in pip_packages(job)))
    if job.backend == "mixle":
        lines.append(f"git clone --depth 1 {shlex.quote(job.repo or '')} repo")
        workdir = "repo"
    else:
        workdir = "."
        lines.append("cat > /workspace/llm_lora_train.py <<'PYEOF'\n" + LLM_LORA_SCRIPT + "\nPYEOF")
    lines.append(f"cd /workspace/{workdir}" if workdir != "." else "cd /workspace")
    lines.append(f"({training_command(job)}) 2>&1 | tee /workspace/train.log")
    if s3_dest:
        lines.append(f"tar czf /workspace/{job.name}.tar.gz {shlex.quote(job.output)}")
        lines.append(f"aws s3 cp /workspace/{job.name}.tar.gz {shlex.quote(s3_dest)} || echo 'upload failed'")
    lines.append("touch /workspace/DONE")
    return "\n".join(lines) + "\n"
