{{- if include "mixle-mlops.needsPVC" . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mixle-mlops.fullname" . }}-data
  labels:
    {{- include "mixle-mlops.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
