{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mixle-mlops.fullname" . }}-secret
  labels:
    {{- include "mixle-mlops.labels" . | nindent 4 }}
type: Opaque
stringData:
  MIXLE_SECRET_KEY: {{ .Values.secretKey | quote }}
  {{- if and .Values.database.url (not .Values.database.existingSecret) }}
  MIXLE_DATABASE_URL: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if and .Values.redis.url (not .Values.redis.existingSecret) }}
  MIXLE_REDIS_URL: {{ .Values.redis.url | quote }}
  {{- end }}
{{- end }}
