"""``init_cloud(provider)`` — a tiny scaffolder that writes a ``.env`` template for a target cloud and prints
the next steps (terraform apply → helm install). Referenced by a future ``mixle-mlops init-cloud <provider>``
CLI subcommand.

It writes *only* a ``.env`` with the right ``MIXLE_*`` keys for the chosen provider's managed services (object
store + Postgres + Redis), pre-filled with placeholders the Terraform outputs replace. It never contacts any
cloud and needs no cloud SDK — it's pure local scaffolding so ``init-cloud`` is instant and offline.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

PROVIDERS = ("aws", "azure", "gcp", "alicloud", "local")


@dataclass
class CloudProfile:
    """Per-provider object-store URL scheme + a human label and the Terraform dir that emits its outputs."""

    name: str
    object_store_example: str
    db_example: str
    redis_example: str
    notes: list[str] = field(default_factory=list)


_PROFILES: dict[str, CloudProfile] = {
    "aws": CloudProfile(
        name="AWS (EKS + S3 + RDS Postgres + ElastiCache Redis)",
        object_store_example="s3://my-mixle-objects",
        db_example="postgresql+psycopg://mixle:CHANGE_ME@my-rds-endpoint:5432/mixle",
        redis_example="redis://my-elasticache-endpoint:6379/0",
        notes=["Pod identity (IRSA) supplies S3 creds — no keys in .env.",
               "terraform/aws outputs object_store_url, database_url, redis_url."],
    ),
    "azure": CloudProfile(
        name="Azure (AKS + Blob Storage + Azure Database for PostgreSQL + Azure Cache for Redis)",
        object_store_example="az://my-mixle-container",
        db_example="postgresql+psycopg://mixle:CHANGE_ME@my-pg.postgres.database.azure.com:5432/mixle",
        redis_example="rediss://my-cache.redis.cache.windows.net:6380/0",
        notes=["Workload identity supplies Blob creds; set MIXLE_OBJECT_STORE_ENDPOINT to the account URL.",
               "terraform/azure outputs object_store_url, database_url, redis_url."],
    ),
    "gcp": CloudProfile(
        name="GCP (GKE + Cloud Storage + Cloud SQL Postgres + Memorystore Redis)",
        object_store_example="gs://my-mixle-objects",
        db_example="postgresql+psycopg://mixle:CHANGE_ME@my-cloudsql-ip:5432/mixle",
        redis_example="redis://my-memorystore-ip:6379/0",
        notes=["Workload Identity supplies GCS creds — no keys in .env.",
               "terraform/gcp outputs object_store_url, database_url, redis_url."],
    ),
    "alicloud": CloudProfile(
        name="Alibaba Cloud (ACK + OSS + ApsaraDB RDS Postgres + ApsaraDB for Redis)",
        object_store_example="oss://my-mixle-objects",
        db_example="postgresql+psycopg://mixle:CHANGE_ME@my-rds-endpoint:5432/mixle",
        redis_example="redis://my-kvstore-endpoint:6379/0",
        notes=["Set MIXLE_OBJECT_STORE_ENDPOINT to the OSS region endpoint (e.g. https://oss-cn-hangzhou.aliyuncs.com).",
               "terraform/alicloud outputs object_store_url, database_url, redis_url."],
    ),
    "local": CloudProfile(
        name="Local (filesystem + SQLite, no cloud)",
        object_store_example="file://./mixle_data/objects",
        db_example="",
        redis_example="",
        notes=["No cloud services; the platform falls back to SQLite + local fs."],
    ),
}


def _env_text(provider: str, profile: CloudProfile) -> str:
    lines = [
        f"# mixle-mlops .env for {profile.name}",
        "# Generated by `mixle-mlops init-cloud %s`. Replace placeholders with `terraform output` values." % provider,
        "",
        'MIXLE_DEPLOYMENT="%s"' % ("local" if provider == "local" else "cloud"),
        'MIXLE_OBJECT_STORE_URL="%s"' % profile.object_store_example,
    ]
    if provider == "alicloud":
        lines.append('MIXLE_OBJECT_STORE_ENDPOINT="https://oss-cn-hangzhou.aliyuncs.com"')
    elif provider == "azure":
        lines.append('# MIXLE_OBJECT_STORE_ENDPOINT="https://<account>.blob.core.windows.net"')
    elif provider == "aws":
        lines.append('# MIXLE_OBJECT_STORE_ENDPOINT="https://s3.us-east-1.amazonaws.com"  # only for S3-compatible')
    if profile.db_example:
        lines.append('MIXLE_DATABASE_URL="%s"' % profile.db_example)
    if profile.redis_example:
        lines.append('MIXLE_REDIS_URL="%s"' % profile.redis_example)
    lines += [
        'MIXLE_SECRET_KEY="CHANGE_ME_to_a_long_random_string"',
        'MIXLE_REQUIRE_AUTH="true"',
        "",
    ]
    return "\n".join(lines)


def init_cloud(provider: str, *, dest: str | Path = ".env", overwrite: bool = False) -> Path:
    """Write a ``.env`` for ``provider`` and return its path. Raises if it exists and ``overwrite`` is False."""
    provider = provider.lower()
    if provider not in _PROFILES:
        raise ValueError(f"unknown provider {provider!r}; choose one of {PROVIDERS}")
    profile = _PROFILES[provider]
    path = Path(dest)
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists; pass overwrite=True to replace it")
    path.write_text(_env_text(provider, profile))
    return path


def next_steps(provider: str) -> str:
    """A copy-pasteable 'what now' string printed after scaffolding."""
    provider = provider.lower()
    profile = _PROFILES[provider]
    tf = "" if provider == "local" else f"deploy/terraform/{provider}"
    out = [f"Scaffolded .env for {profile.name}.", ""]
    for n in profile.notes:
        out.append(f"  - {n}")
    out.append("")
    if provider == "local":
        out += ["Next:", "  mixle-serve   # runs on http://localhost:8000 with SQLite + local fs"]
    else:
        out += [
            "Next:",
            f"  1) cd {tf} && terraform init && terraform apply",
            "  2) copy the terraform outputs (object_store_url/database_url/redis_url) into .env",
            "  3) helm upgrade --install mixle-mlops deploy/helm/mixle-mlops \\",
            "         --set-file env.fromDotenv=.env   # or --set env.MIXLE_OBJECT_STORE_URL=...",
            "",
            "Same image + chart on every cloud — only the object store + db + redis URLs change.",
        ]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> None:
    """Console-ish entry for ``mixle-mlops init-cloud <provider> [--dest .env] [--force]``."""
    import argparse

    p = argparse.ArgumentParser(prog="mixle-mlops init-cloud", description="scaffold a cloud .env")
    p.add_argument("provider", choices=PROVIDERS)
    p.add_argument("--dest", default=".env")
    p.add_argument("--force", action="store_true", help="overwrite an existing .env")
    args = p.parse_args(argv)
    path = init_cloud(args.provider, dest=args.dest, overwrite=args.force)
    print(f"wrote {path}")
    print(next_steps(args.provider))


if __name__ == "__main__":  # pragma: no cover
    main()
